-- Passive Portfolio Lab Looker Studio semantic layer
-- Generated by looker_studio/generate_bigquery_views.py
-- Run this file in BigQuery, then connect Looker Studio to the views below.

CREATE OR REPLACE VIEW `passive-portfolio-lab.passive_portfolio.looker_asset_metrics` AS
WITH
asset_metadata AS (
  SELECT * FROM UNNEST([
    STRUCT('0050.TW' AS ticker, 'Yuanta Taiwan 50 ETF' AS name, 'TW_ETF' AS category, 'Market-Cap' AS subcategory, 1 AS aum_rank, 'approx. TWD 1,661.5B' AS aum_note, 'Tracks the top 50 Taiwan companies by market cap; the core passive investment vehicle for the Taiwan stock market.' AS description),
    STRUCT('0056.TW' AS ticker, 'Yuanta High Dividend ETF' AS name, 'TW_ETF' AS category, 'High Dividend' AS subcategory, 2 AS aum_rank, 'approx. TWD 584.1B' AS aum_note, 'Selects the 30 Taiwan stocks with the highest forecast cash dividend yield; the flagship high-dividend ETF in Taiwan.' AS description),
    STRUCT('00878.TW' AS ticker, 'Cathay Sustainable High Dividend ETF' AS name, 'TW_ETF' AS category, 'High Dividend / ESG' AS subcategory, 3 AS aum_rank, 'approx. TWD 485.4B' AS aum_note, 'Combines ESG screening with a high-dividend strategy; pays quarterly dividends.' AS description),
    STRUCT('00919.TW' AS ticker, 'Group Benefits Taiwan Select High Yield ETF' AS name, 'TW_ETF' AS category, 'High Dividend' AS subcategory, 4 AS aum_rank, 'approx. TWD 451.8B' AS aum_note, 'High-dividend plus multi-factor stock selection; monthly distributions; fast-growing AUM.' AS description),
    STRUCT('006208.TW' AS ticker, 'Fubon Taiwan 50 ETF' AS name, 'TW_ETF' AS category, 'Market-Cap' AS subcategory, 5 AS aum_rank, 'approx. TWD 389.4B' AS aum_note, 'Also tracks the Taiwan 50 index; a competitor to 0050 with a lower expense ratio.' AS description),
    STRUCT('00937B.TWO' AS ticker, 'Group Benefits ESG IG Bond 20+ ETF' AS name, 'TW_ETF' AS category, 'Bond' AS subcategory, 6 AS aum_rank, 'approx. TWD 267.9B' AS aum_note, 'Invests in ESG investment-grade corporate bonds with 20+ year maturities; monthly distributions.' AS description),
    STRUCT('00679B.TWO' AS ticker, 'Yuanta US Treasury 20+ Year ETF' AS name, 'TW_ETF' AS category, 'Bond' AS subcategory, 8 AS aum_rank, 'approx. TWD 203.7B' AS aum_note, 'Tracks 20-year US Treasuries; the primary tool for holding long-duration US bonds in TWD.' AS description),
    STRUCT('00751B.TWO' AS ticker, 'Yuanta AAA-A Corporate Bond ETF' AS name, 'TW_ETF' AS category, 'Bond' AS subcategory, 9 AS aum_rank, 'approx. TWD 180.0B' AS aum_note, 'Invests in highly-rated US corporate bonds, balancing yield with credit quality.' AS description),
    STRUCT('0052.TW' AS ticker, 'Fubon Technology ETF' AS name, 'TW_ETF' AS category, 'Technology Theme' AS subcategory, 10 AS aum_rank, 'approx. TWD 132.0B' AS aum_note, 'Tracks the Taiwan Technology Index; top holdings include TSMC and MediaTek.' AS description),
    STRUCT('00929.TW' AS ticker, 'Fuh Hwa Taiwan Tech High Yield ETF' AS name, 'TW_ETF' AS category, 'Tech High Dividend' AS subcategory, 11 AS aum_rank, 'approx. TWD 115.2B' AS aum_note, 'Technology stocks combined with a high-dividend strategy; Taiwan\'s first monthly-dividend ETF.' AS description),
    STRUCT('00713.TW' AS ticker, 'Yuanta Taiwan High Dividend Low Volatility ETF' AS name, 'TW_ETF' AS category, 'High Dividend Low Vol' AS subcategory, 12 AS aum_rank, 'approx. TWD 113.0B' AS aum_note, 'Combines high dividend and low-volatility factors; suited for conservative investors.' AS description),
    STRUCT('00952.TW' AS ticker, 'KGI Taiwan AI 50 ETF' AS name, 'TW_ETF' AS category, 'AI Theme' AS subcategory, 14 AS aum_rank, 'approx. TWD 60.0B' AS aum_note, 'Top 50 companies in Taiwan\'s AI supply chain; high-purity AI theme with monthly distributions.' AS description),
    STRUCT('00646.TW' AS ticker, 'Yuanta S&P 500 ETF' AS name, 'TW_ETF' AS category, 'S&P 500 Exposure' AS subcategory, 99 AS aum_rank, 'approx. TWD 25.0B' AS aum_note, 'Tracks the S&P 500 index in TWD; provides US large-cap exposure without currency conversion. Owner addition.' AS description),
    STRUCT('00955.TWO' AS ticker, 'CTBC Japan Sogo Shosha ETF' AS name, 'TW_ETF' AS category, 'Japan Sogo Shosha' AS subcategory, 99 AS aum_rank, 'approx. TWD 5.0B' AS aum_note, 'Tracks Japan\'s five major trading conglomerates (sogo shosha). Limited history since 2023 — metrics are indicative. Owner addition.' AS description),
    STRUCT('VOO' AS ticker, 'Vanguard S&P 500 ETF' AS name, 'US_ETF' AS category, 'US Large-Cap Blend' AS subcategory, 1 AS aum_rank, 'approx. USD 827.0B' AS aum_note, 'The world\'s largest ETF; tracks the S&P 500 with a 0.03% expense ratio.' AS description),
    STRUCT('IVV' AS ticker, 'iShares Core S&P 500 ETF' AS name, 'US_ETF' AS category, 'US Large-Cap Blend' AS subcategory, 2 AS aum_rank, 'approx. USD 766.0B' AS aum_note, 'Also tracks the S&P 500; managed by BlackRock and preferred by institutional investors.' AS description),
    STRUCT('SPY' AS ticker, 'SPDR S&P 500 ETF Trust' AS name, 'US_ETF' AS category, 'US Large-Cap Blend' AS subcategory, 3 AS aum_rank, 'approx. USD 672.0B' AS aum_note, 'The oldest S&P 500 ETF; highest liquidity in the options market.' AS description),
    STRUCT('VTI' AS ticker, 'Vanguard Total Stock Market ETF' AS name, 'US_ETF' AS category, 'US Total Market' AS subcategory, 4 AS aum_rank, 'approx. USD 586.0B' AS aum_note, 'Covers ~3,700 US large-, mid-, and small-cap stocks; expense ratio 0.03%.' AS description),
    STRUCT('QQQ' AS ticker, 'Invesco QQQ Trust' AS name, 'US_ETF' AS category, 'US Technology Growth' AS subcategory, 5 AS aum_rank, 'approx. USD 400.0B' AS aum_note, 'Tracks the NASDAQ-100; tech-concentrated with 10-year annualized returns above 18%.' AS description),
    STRUCT('VUG' AS ticker, 'Vanguard Growth ETF' AS name, 'US_ETF' AS category, 'US Growth' AS subcategory, 6 AS aum_rank, 'approx. USD 207.4B' AS aum_note, 'Large-cap growth stocks with high tech exposure; expense ratio 0.04%.' AS description),
    STRUCT('VEA' AS ticker, 'Vanguard FTSE Developed Markets ETF' AS name, 'US_ETF' AS category, 'Developed International' AS subcategory, 7 AS aum_rank, 'approx. USD 219.9B' AS aum_note, 'Covers developed markets outside the US, including Europe, Japan, and Canada.' AS description),
    STRUCT('IEFA' AS ticker, 'iShares Core MSCI EAFE ETF' AS name, 'US_ETF' AS category, 'Developed International' AS subcategory, 8 AS aum_rank, 'approx. USD 180.9B' AS aum_note, 'Tracks the MSCI EAFE index (excluding Canada); primarily Europe and Japan.' AS description),
    STRUCT('VTV' AS ticker, 'Vanguard Value ETF' AS name, 'US_ETF' AS category, 'US Value' AS subcategory, 9 AS aum_rank, 'approx. USD 169.3B' AS aum_note, 'Large-cap value stocks with low P/E and high dividend yield; a natural pair with VUG.' AS description),
    STRUCT('GLD' AS ticker, 'SPDR Gold Shares' AS name, 'US_ETF' AS category, 'Gold / Commodities' AS subcategory, 10 AS aum_rank, 'approx. USD 163.4B' AS aum_note, 'The world\'s largest physically-backed gold ETF; hedges inflation and systemic risk.' AS description),
    STRUCT('BND' AS ticker, 'Vanguard Total Bond Market ETF' AS name, 'US_ETF' AS category, 'US Total Bond' AS subcategory, 11 AS aum_rank, 'approx. USD 152.6B' AS aum_note, 'Covers US investment-grade government and corporate bonds; expense ratio 0.03%.' AS description),
    STRUCT('IEMG' AS ticker, 'iShares Core MSCI Emerging Markets ETF' AS name, 'US_ETF' AS category, 'Emerging Markets' AS subcategory, 12 AS aum_rank, 'approx. USD 148.9B' AS aum_note, 'Tracks the MSCI Emerging Markets index; top three exposures are China, India, and Brazil.' AS description),
    STRUCT('VXUS' AS ticker, 'Vanguard Total International Stock ETF' AS name, 'US_ETF' AS category, 'Global ex-US' AS subcategory, 13 AS aum_rank, 'approx. USD 144.0B' AS aum_note, 'Covers both developed and emerging markets outside the US in a single fund.' AS description),
    STRUCT('AGG' AS ticker, 'iShares Core U.S. Aggregate Bond ETF' AS name, 'US_ETF' AS category, 'US Total Bond' AS subcategory, 14 AS aum_rank, 'approx. USD 135.9B' AS aum_note, 'Tracks the Bloomberg US Aggregate Bond Index; highly similar to BND.' AS description),
    STRUCT('IEF' AS ticker, 'iShares 7-10 Year Treasury Bond ETF' AS name, 'US_ETF' AS category, 'Intermediate US Treasury' AS subcategory, 15 AS aum_rank, 'approx. USD 45.0B' AS aum_note, 'Moderate interest-rate sensitivity; commonly used as an equity hedge.' AS description),
    STRUCT('BTC-USD' AS ticker, 'Bitcoin' AS name, 'CRYPTO' AS category, 'Store of Value' AS subcategory, 1 AS aum_rank, 'approx. USD 1,300.0B' AS aum_note, '~58% market dominance; digital gold and the preferred crypto asset for institutional holdings.' AS description),
    STRUCT('ETH-USD' AS ticker, 'Ethereum' AS name, 'CRYPTO' AS category, 'Smart Contract Platform' AS subcategory, 2 AS aum_rank, 'approx. USD 280.0B' AS aum_note, 'Core infrastructure for DeFi, NFTs, and Layer 2; the world\'s second-largest cryptocurrency.' AS description),
    STRUCT('BNB-USD' AS ticker, 'BNB' AS name, 'CRYPTO' AS category, 'Exchange Platform Token' AS subcategory, 3 AS aum_rank, 'approx. USD 85.0B' AS aum_note, 'Native token of the Binance ecosystem and BNB Chain; features a periodic token-burn mechanism.' AS description),
    STRUCT('XRP-USD' AS ticker, 'XRP' AS name, 'CRYPTO' AS category, 'Cross-Border Payments' AS subcategory, 4 AS aum_rank, 'approx. USD 65.0B' AS aum_note, 'Led by Ripple; focused on institutional cross-border settlement with 3–5 second finality.' AS description),
    STRUCT('SOL-USD' AS ticker, 'Solana' AS name, 'CRYPTO' AS category, 'High-Performance L1' AS subcategory, 5 AS aum_rank, 'approx. USD 65.0B' AS aum_note, 'High throughput and low fees; one of the most active chains for DeFi and meme coins.' AS description),
    STRUCT('TRX-USD' AS ticker, 'TRON' AS name, 'CRYPTO' AS category, 'Stablecoin Settlement Chain' AS subcategory, 6 AS aum_rank, 'approx. USD 25.0B' AS aum_note, 'The largest chain for USDT on-chain activity; low-fee stablecoin ecosystem.' AS description),
    STRUCT('DOGE-USD' AS ticker, 'Dogecoin' AS name, 'CRYPTO' AS category, 'Meme Coin' AS subcategory, 7 AS aum_rank, 'approx. USD 25.0B' AS aum_note, 'The most liquid meme coin; PoW consensus mechanism with a strong community following.' AS description),
    STRUCT('ADA-USD' AS ticker, 'Cardano' AS name, 'CRYPTO' AS category, 'Academic L1' AS subcategory, 8 AS aum_rank, 'approx. USD 20.0B' AS aum_note, 'Research-driven development; PoS consensus with regulatory compliance focus and mature governance.' AS description)
  ])
)
SELECT
  m.ticker,
  md.name,
  md.category,
  md.subcategory,
  md.aum_rank,
  md.aum_note,
  md.description,
  CASE WHEN md.category = 'TW_ETF' THEN 'TWD' ELSE 'USD' END AS currency,
  DATE(m.data_start) AS data_start,
  DATE(m.data_end) AS data_end,
  m.cagr,
  m.volatility,
  m.max_drawdown,
  m.sharpe_ratio,
  m.recovery_period_days,
  m.recovery_status,
  m.worst_year,
  m.worst_year_label,
  ROUND(m.cagr * 100, 2) AS cagr_pct,
  ROUND(m.volatility * 100, 2) AS volatility_pct,
  ROUND(m.max_drawdown * 100, 2) AS max_drawdown_pct,
  ROUND(m.worst_year * 100, 2) AS worst_year_pct
FROM `passive-portfolio-lab.passive_portfolio.asset_metrics` AS m
LEFT JOIN asset_metadata AS md USING (ticker);

CREATE OR REPLACE VIEW `passive-portfolio-lab.passive_portfolio.looker_price_history` AS
WITH
asset_metadata AS (
  SELECT * FROM UNNEST([
    STRUCT('0050.TW' AS ticker, 'Yuanta Taiwan 50 ETF' AS name, 'TW_ETF' AS category, 'Market-Cap' AS subcategory, 1 AS aum_rank, 'approx. TWD 1,661.5B' AS aum_note, 'Tracks the top 50 Taiwan companies by market cap; the core passive investment vehicle for the Taiwan stock market.' AS description),
    STRUCT('0056.TW' AS ticker, 'Yuanta High Dividend ETF' AS name, 'TW_ETF' AS category, 'High Dividend' AS subcategory, 2 AS aum_rank, 'approx. TWD 584.1B' AS aum_note, 'Selects the 30 Taiwan stocks with the highest forecast cash dividend yield; the flagship high-dividend ETF in Taiwan.' AS description),
    STRUCT('00878.TW' AS ticker, 'Cathay Sustainable High Dividend ETF' AS name, 'TW_ETF' AS category, 'High Dividend / ESG' AS subcategory, 3 AS aum_rank, 'approx. TWD 485.4B' AS aum_note, 'Combines ESG screening with a high-dividend strategy; pays quarterly dividends.' AS description),
    STRUCT('00919.TW' AS ticker, 'Group Benefits Taiwan Select High Yield ETF' AS name, 'TW_ETF' AS category, 'High Dividend' AS subcategory, 4 AS aum_rank, 'approx. TWD 451.8B' AS aum_note, 'High-dividend plus multi-factor stock selection; monthly distributions; fast-growing AUM.' AS description),
    STRUCT('006208.TW' AS ticker, 'Fubon Taiwan 50 ETF' AS name, 'TW_ETF' AS category, 'Market-Cap' AS subcategory, 5 AS aum_rank, 'approx. TWD 389.4B' AS aum_note, 'Also tracks the Taiwan 50 index; a competitor to 0050 with a lower expense ratio.' AS description),
    STRUCT('00937B.TWO' AS ticker, 'Group Benefits ESG IG Bond 20+ ETF' AS name, 'TW_ETF' AS category, 'Bond' AS subcategory, 6 AS aum_rank, 'approx. TWD 267.9B' AS aum_note, 'Invests in ESG investment-grade corporate bonds with 20+ year maturities; monthly distributions.' AS description),
    STRUCT('00679B.TWO' AS ticker, 'Yuanta US Treasury 20+ Year ETF' AS name, 'TW_ETF' AS category, 'Bond' AS subcategory, 8 AS aum_rank, 'approx. TWD 203.7B' AS aum_note, 'Tracks 20-year US Treasuries; the primary tool for holding long-duration US bonds in TWD.' AS description),
    STRUCT('00751B.TWO' AS ticker, 'Yuanta AAA-A Corporate Bond ETF' AS name, 'TW_ETF' AS category, 'Bond' AS subcategory, 9 AS aum_rank, 'approx. TWD 180.0B' AS aum_note, 'Invests in highly-rated US corporate bonds, balancing yield with credit quality.' AS description),
    STRUCT('0052.TW' AS ticker, 'Fubon Technology ETF' AS name, 'TW_ETF' AS category, 'Technology Theme' AS subcategory, 10 AS aum_rank, 'approx. TWD 132.0B' AS aum_note, 'Tracks the Taiwan Technology Index; top holdings include TSMC and MediaTek.' AS description),
    STRUCT('00929.TW' AS ticker, 'Fuh Hwa Taiwan Tech High Yield ETF' AS name, 'TW_ETF' AS category, 'Tech High Dividend' AS subcategory, 11 AS aum_rank, 'approx. TWD 115.2B' AS aum_note, 'Technology stocks combined with a high-dividend strategy; Taiwan\'s first monthly-dividend ETF.' AS description),
    STRUCT('00713.TW' AS ticker, 'Yuanta Taiwan High Dividend Low Volatility ETF' AS name, 'TW_ETF' AS category, 'High Dividend Low Vol' AS subcategory, 12 AS aum_rank, 'approx. TWD 113.0B' AS aum_note, 'Combines high dividend and low-volatility factors; suited for conservative investors.' AS description),
    STRUCT('00952.TW' AS ticker, 'KGI Taiwan AI 50 ETF' AS name, 'TW_ETF' AS category, 'AI Theme' AS subcategory, 14 AS aum_rank, 'approx. TWD 60.0B' AS aum_note, 'Top 50 companies in Taiwan\'s AI supply chain; high-purity AI theme with monthly distributions.' AS description),
    STRUCT('00646.TW' AS ticker, 'Yuanta S&P 500 ETF' AS name, 'TW_ETF' AS category, 'S&P 500 Exposure' AS subcategory, 99 AS aum_rank, 'approx. TWD 25.0B' AS aum_note, 'Tracks the S&P 500 index in TWD; provides US large-cap exposure without currency conversion. Owner addition.' AS description),
    STRUCT('00955.TWO' AS ticker, 'CTBC Japan Sogo Shosha ETF' AS name, 'TW_ETF' AS category, 'Japan Sogo Shosha' AS subcategory, 99 AS aum_rank, 'approx. TWD 5.0B' AS aum_note, 'Tracks Japan\'s five major trading conglomerates (sogo shosha). Limited history since 2023 — metrics are indicative. Owner addition.' AS description),
    STRUCT('VOO' AS ticker, 'Vanguard S&P 500 ETF' AS name, 'US_ETF' AS category, 'US Large-Cap Blend' AS subcategory, 1 AS aum_rank, 'approx. USD 827.0B' AS aum_note, 'The world\'s largest ETF; tracks the S&P 500 with a 0.03% expense ratio.' AS description),
    STRUCT('IVV' AS ticker, 'iShares Core S&P 500 ETF' AS name, 'US_ETF' AS category, 'US Large-Cap Blend' AS subcategory, 2 AS aum_rank, 'approx. USD 766.0B' AS aum_note, 'Also tracks the S&P 500; managed by BlackRock and preferred by institutional investors.' AS description),
    STRUCT('SPY' AS ticker, 'SPDR S&P 500 ETF Trust' AS name, 'US_ETF' AS category, 'US Large-Cap Blend' AS subcategory, 3 AS aum_rank, 'approx. USD 672.0B' AS aum_note, 'The oldest S&P 500 ETF; highest liquidity in the options market.' AS description),
    STRUCT('VTI' AS ticker, 'Vanguard Total Stock Market ETF' AS name, 'US_ETF' AS category, 'US Total Market' AS subcategory, 4 AS aum_rank, 'approx. USD 586.0B' AS aum_note, 'Covers ~3,700 US large-, mid-, and small-cap stocks; expense ratio 0.03%.' AS description),
    STRUCT('QQQ' AS ticker, 'Invesco QQQ Trust' AS name, 'US_ETF' AS category, 'US Technology Growth' AS subcategory, 5 AS aum_rank, 'approx. USD 400.0B' AS aum_note, 'Tracks the NASDAQ-100; tech-concentrated with 10-year annualized returns above 18%.' AS description),
    STRUCT('VUG' AS ticker, 'Vanguard Growth ETF' AS name, 'US_ETF' AS category, 'US Growth' AS subcategory, 6 AS aum_rank, 'approx. USD 207.4B' AS aum_note, 'Large-cap growth stocks with high tech exposure; expense ratio 0.04%.' AS description),
    STRUCT('VEA' AS ticker, 'Vanguard FTSE Developed Markets ETF' AS name, 'US_ETF' AS category, 'Developed International' AS subcategory, 7 AS aum_rank, 'approx. USD 219.9B' AS aum_note, 'Covers developed markets outside the US, including Europe, Japan, and Canada.' AS description),
    STRUCT('IEFA' AS ticker, 'iShares Core MSCI EAFE ETF' AS name, 'US_ETF' AS category, 'Developed International' AS subcategory, 8 AS aum_rank, 'approx. USD 180.9B' AS aum_note, 'Tracks the MSCI EAFE index (excluding Canada); primarily Europe and Japan.' AS description),
    STRUCT('VTV' AS ticker, 'Vanguard Value ETF' AS name, 'US_ETF' AS category, 'US Value' AS subcategory, 9 AS aum_rank, 'approx. USD 169.3B' AS aum_note, 'Large-cap value stocks with low P/E and high dividend yield; a natural pair with VUG.' AS description),
    STRUCT('GLD' AS ticker, 'SPDR Gold Shares' AS name, 'US_ETF' AS category, 'Gold / Commodities' AS subcategory, 10 AS aum_rank, 'approx. USD 163.4B' AS aum_note, 'The world\'s largest physically-backed gold ETF; hedges inflation and systemic risk.' AS description),
    STRUCT('BND' AS ticker, 'Vanguard Total Bond Market ETF' AS name, 'US_ETF' AS category, 'US Total Bond' AS subcategory, 11 AS aum_rank, 'approx. USD 152.6B' AS aum_note, 'Covers US investment-grade government and corporate bonds; expense ratio 0.03%.' AS description),
    STRUCT('IEMG' AS ticker, 'iShares Core MSCI Emerging Markets ETF' AS name, 'US_ETF' AS category, 'Emerging Markets' AS subcategory, 12 AS aum_rank, 'approx. USD 148.9B' AS aum_note, 'Tracks the MSCI Emerging Markets index; top three exposures are China, India, and Brazil.' AS description),
    STRUCT('VXUS' AS ticker, 'Vanguard Total International Stock ETF' AS name, 'US_ETF' AS category, 'Global ex-US' AS subcategory, 13 AS aum_rank, 'approx. USD 144.0B' AS aum_note, 'Covers both developed and emerging markets outside the US in a single fund.' AS description),
    STRUCT('AGG' AS ticker, 'iShares Core U.S. Aggregate Bond ETF' AS name, 'US_ETF' AS category, 'US Total Bond' AS subcategory, 14 AS aum_rank, 'approx. USD 135.9B' AS aum_note, 'Tracks the Bloomberg US Aggregate Bond Index; highly similar to BND.' AS description),
    STRUCT('IEF' AS ticker, 'iShares 7-10 Year Treasury Bond ETF' AS name, 'US_ETF' AS category, 'Intermediate US Treasury' AS subcategory, 15 AS aum_rank, 'approx. USD 45.0B' AS aum_note, 'Moderate interest-rate sensitivity; commonly used as an equity hedge.' AS description),
    STRUCT('BTC-USD' AS ticker, 'Bitcoin' AS name, 'CRYPTO' AS category, 'Store of Value' AS subcategory, 1 AS aum_rank, 'approx. USD 1,300.0B' AS aum_note, '~58% market dominance; digital gold and the preferred crypto asset for institutional holdings.' AS description),
    STRUCT('ETH-USD' AS ticker, 'Ethereum' AS name, 'CRYPTO' AS category, 'Smart Contract Platform' AS subcategory, 2 AS aum_rank, 'approx. USD 280.0B' AS aum_note, 'Core infrastructure for DeFi, NFTs, and Layer 2; the world\'s second-largest cryptocurrency.' AS description),
    STRUCT('BNB-USD' AS ticker, 'BNB' AS name, 'CRYPTO' AS category, 'Exchange Platform Token' AS subcategory, 3 AS aum_rank, 'approx. USD 85.0B' AS aum_note, 'Native token of the Binance ecosystem and BNB Chain; features a periodic token-burn mechanism.' AS description),
    STRUCT('XRP-USD' AS ticker, 'XRP' AS name, 'CRYPTO' AS category, 'Cross-Border Payments' AS subcategory, 4 AS aum_rank, 'approx. USD 65.0B' AS aum_note, 'Led by Ripple; focused on institutional cross-border settlement with 3–5 second finality.' AS description),
    STRUCT('SOL-USD' AS ticker, 'Solana' AS name, 'CRYPTO' AS category, 'High-Performance L1' AS subcategory, 5 AS aum_rank, 'approx. USD 65.0B' AS aum_note, 'High throughput and low fees; one of the most active chains for DeFi and meme coins.' AS description),
    STRUCT('TRX-USD' AS ticker, 'TRON' AS name, 'CRYPTO' AS category, 'Stablecoin Settlement Chain' AS subcategory, 6 AS aum_rank, 'approx. USD 25.0B' AS aum_note, 'The largest chain for USDT on-chain activity; low-fee stablecoin ecosystem.' AS description),
    STRUCT('DOGE-USD' AS ticker, 'Dogecoin' AS name, 'CRYPTO' AS category, 'Meme Coin' AS subcategory, 7 AS aum_rank, 'approx. USD 25.0B' AS aum_note, 'The most liquid meme coin; PoW consensus mechanism with a strong community following.' AS description),
    STRUCT('ADA-USD' AS ticker, 'Cardano' AS name, 'CRYPTO' AS category, 'Academic L1' AS subcategory, 8 AS aum_rank, 'approx. USD 20.0B' AS aum_note, 'Research-driven development; PoS consensus with regulatory compliance focus and mature governance.' AS description)
  ])
),
prices AS (
  SELECT
    DATE(date) AS date,
    ticker,
    SAFE_CAST(close AS FLOAT64) AS close
  FROM `passive-portfolio-lab.passive_portfolio.raw_prices`
  WHERE close IS NOT NULL
),
enriched AS (
  SELECT
    p.date,
    p.ticker,
    md.name,
    md.category,
    md.subcategory,
    CASE WHEN md.category = 'TW_ETF' THEN 'TWD' ELSE 'USD' END AS currency,
    p.close,
    LAG(p.close) OVER (PARTITION BY p.ticker ORDER BY p.date) AS previous_close,
    FIRST_VALUE(p.close) OVER (
      PARTITION BY p.ticker
      ORDER BY p.date
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS first_close
  FROM prices AS p
  LEFT JOIN asset_metadata AS md USING (ticker)
)
SELECT
  date,
  ticker,
  name,
  category,
  subcategory,
  currency,
  close,
  SAFE_DIVIDE(close, previous_close) - 1 AS daily_return,
  SAFE_DIVIDE(close, first_close) - 1 AS cumulative_return,
  ROUND((SAFE_DIVIDE(close, previous_close) - 1) * 100, 4) AS daily_return_pct,
  ROUND((SAFE_DIVIDE(close, first_close) - 1) * 100, 2) AS cumulative_return_pct
FROM enriched;

CREATE OR REPLACE VIEW `passive-portfolio-lab.passive_portfolio.looker_annual_returns` AS
WITH yearly AS (
  SELECT
    EXTRACT(YEAR FROM date) AS year,
    ticker,
    name,
    category,
    subcategory,
    currency,
    ARRAY_AGG(close ORDER BY date ASC LIMIT 1)[OFFSET(0)] AS first_close,
    ARRAY_AGG(close ORDER BY date DESC LIMIT 1)[OFFSET(0)] AS last_close
  FROM `passive-portfolio-lab.passive_portfolio.looker_price_history`
  GROUP BY year, ticker, name, category, subcategory, currency
)
SELECT
  year,
  ticker,
  name,
  category,
  subcategory,
  currency,
  SAFE_DIVIDE(last_close, first_close) - 1 AS annual_return,
  ROUND((SAFE_DIVIDE(last_close, first_close) - 1) * 100, 2) AS annual_return_pct
FROM yearly;

CREATE OR REPLACE VIEW `passive-portfolio-lab.passive_portfolio.looker_category_summary` AS
SELECT
  category,
  COUNT(*) AS asset_count,
  AVG(cagr) AS avg_cagr,
  AVG(volatility) AS avg_volatility,
  AVG(max_drawdown) AS avg_max_drawdown,
  AVG(sharpe_ratio) AS avg_sharpe_ratio,
  ROUND(AVG(cagr) * 100, 2) AS avg_cagr_pct,
  ROUND(AVG(volatility) * 100, 2) AS avg_volatility_pct,
  ROUND(AVG(max_drawdown) * 100, 2) AS avg_max_drawdown_pct
FROM `passive-portfolio-lab.passive_portfolio.looker_asset_metrics`
GROUP BY category;
