#!/usr/bin/env python3
"""
Generate BigQuery views for Looker Studio.

The output SQL creates a small semantic layer on top of the existing
raw_prices and asset_metrics tables used by Passive Portfolio Lab.

Usage:
    GOOGLE_CLOUD_PROJECT=your-project BIGQUERY_DATASET=portfolio \
        python3 looker_studio/generate_bigquery_views.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path(__file__).resolve().parent / "bigquery_views.sql"
sys.path.append(str(REPO_ROOT / "streamlit_dashboard"))

from src.processing.screening import ASSET_POOL  # noqa: E402
from src.processing.utils import validate_bq_identifier  # noqa: E402


def sql_string(value: object) -> str:
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def asset_metadata_cte() -> str:
    rows = []
    for asset in ASSET_POOL:
        rows.append(
            "    STRUCT("
            f"{sql_string(asset['ticker'])} AS ticker, "
            f"{sql_string(asset['name'])} AS name, "
            f"{sql_string(asset['category'])} AS category, "
            f"{sql_string(asset['subcategory'])} AS subcategory, "
            f"{int(asset['aum_rank'])} AS aum_rank, "
            f"{sql_string(asset['aum_note'])} AS aum_note, "
            f"{sql_string(asset['description'])} AS description"
            ")"
        )
    # ASSET_POOL is a fixed repo-local curated list, not runtime user input.
    return "asset_metadata AS (\n  SELECT * FROM UNNEST([\n" + ",\n".join(rows) + "\n  ])\n)"  # nosec B608


def build_sql(project_id: str, dataset_id: str) -> str:
    table_prefix = f"`{project_id}.{dataset_id}"
    metadata = asset_metadata_cte()
    # project_id and dataset_id are validated in main(); metadata comes from ASSET_POOL.
    sql = f"""-- Passive Portfolio Lab Looker Studio semantic layer
-- Generated by looker_studio/generate_bigquery_views.py
-- Run this file in BigQuery, then connect Looker Studio to the views below.

CREATE OR REPLACE VIEW `{project_id}.{dataset_id}.looker_asset_metrics` AS
WITH
{metadata}
SELECT
  m.ticker,
  md.name,
  md.category,
  md.subcategory,
  md.aum_rank,
  md.aum_note,
  md.description,
  CASE WHEN md.category = 'TW_ETF' THEN 'TWD' ELSE 'USD' END AS currency,
  DATE(m.data_start) AS data_start,
  DATE(m.data_end) AS data_end,
  m.cagr,
  m.volatility,
  m.max_drawdown,
  m.sharpe_ratio,
  m.recovery_period_days,
  m.recovery_status,
  m.worst_year,
  m.worst_year_label,
  ROUND(m.cagr * 100, 2) AS cagr_pct,
  ROUND(m.volatility * 100, 2) AS volatility_pct,
  ROUND(m.max_drawdown * 100, 2) AS max_drawdown_pct,
  ROUND(m.worst_year * 100, 2) AS worst_year_pct
FROM {table_prefix}.asset_metrics` AS m
LEFT JOIN asset_metadata AS md USING (ticker);

CREATE OR REPLACE VIEW `{project_id}.{dataset_id}.looker_price_history` AS
WITH
{metadata},
prices AS (
  SELECT
    DATE(date) AS date,
    ticker,
    SAFE_CAST(close AS FLOAT64) AS close
  FROM {table_prefix}.raw_prices`
  WHERE close IS NOT NULL
),
enriched AS (
  SELECT
    p.date,
    p.ticker,
    md.name,
    md.category,
    md.subcategory,
    CASE WHEN md.category = 'TW_ETF' THEN 'TWD' ELSE 'USD' END AS currency,
    p.close,
    LAG(p.close) OVER (PARTITION BY p.ticker ORDER BY p.date) AS previous_close,
    FIRST_VALUE(p.close) OVER (
      PARTITION BY p.ticker
      ORDER BY p.date
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS first_close
  FROM prices AS p
  LEFT JOIN asset_metadata AS md USING (ticker)
)
SELECT
  date,
  ticker,
  name,
  category,
  subcategory,
  currency,
  close,
  SAFE_DIVIDE(close, previous_close) - 1 AS daily_return,
  SAFE_DIVIDE(close, first_close) - 1 AS cumulative_return,
  ROUND((SAFE_DIVIDE(close, previous_close) - 1) * 100, 4) AS daily_return_pct,
  ROUND((SAFE_DIVIDE(close, first_close) - 1) * 100, 2) AS cumulative_return_pct
FROM enriched;

CREATE OR REPLACE VIEW `{project_id}.{dataset_id}.looker_annual_returns` AS
WITH yearly AS (
  SELECT
    EXTRACT(YEAR FROM date) AS year,
    ticker,
    name,
    category,
    subcategory,
    currency,
    ARRAY_AGG(close ORDER BY date ASC LIMIT 1)[OFFSET(0)] AS first_close,
    ARRAY_AGG(close ORDER BY date DESC LIMIT 1)[OFFSET(0)] AS last_close
  FROM `{project_id}.{dataset_id}.looker_price_history`
  GROUP BY year, ticker, name, category, subcategory, currency
)
SELECT
  year,
  ticker,
  name,
  category,
  subcategory,
  currency,
  SAFE_DIVIDE(last_close, first_close) - 1 AS annual_return,
  ROUND((SAFE_DIVIDE(last_close, first_close) - 1) * 100, 2) AS annual_return_pct
FROM yearly;

CREATE OR REPLACE VIEW `{project_id}.{dataset_id}.looker_category_summary` AS
SELECT
  category,
  COUNT(*) AS asset_count,
  AVG(cagr) AS avg_cagr,
  AVG(volatility) AS avg_volatility,
  AVG(max_drawdown) AS avg_max_drawdown,
  AVG(sharpe_ratio) AS avg_sharpe_ratio,
  ROUND(AVG(cagr) * 100, 2) AS avg_cagr_pct,
  ROUND(AVG(volatility) * 100, 2) AS avg_volatility_pct,
  ROUND(AVG(max_drawdown) * 100, 2) AS avg_max_drawdown_pct
FROM `{project_id}.{dataset_id}.looker_asset_metrics`
GROUP BY category;
"""  # nosec B608
    return sql


def main() -> None:
    project_id = os.getenv("GOOGLE_CLOUD_PROJECT")
    dataset_id = os.getenv("BIGQUERY_DATASET")
    if not project_id or not dataset_id:
        raise SystemExit(
            "Missing GOOGLE_CLOUD_PROJECT or BIGQUERY_DATASET. "
            "Set them in .env or pass them as environment variables."
        )
    project_id = validate_bq_identifier(project_id, "project id")
    dataset_id = validate_bq_identifier(dataset_id, "dataset id")

    OUTPUT.write_text(build_sql(project_id, dataset_id), encoding="utf-8")
    print(f"Generated {OUTPUT}")


if __name__ == "__main__":
    main()
